# Generated by Django 5.1.4 on 2025-04-17 10:38

import django.db.models.deletion
import django.utils.timezone
import ideaGen.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Idea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("decomposed_aspects", models.JSONField(blank=True, null=True)),
                ("enhanced_description", models.TextField(blank=True, null=True)),
                ("visualization_prompt", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("original_idea_id", models.IntegerField(blank=True, null=True)),
                ("idea_set", models.IntegerField(default=1)),
                ("idea_set_label", models.CharField(default="Set 1-1", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="GeneratedImage2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=ideaGen.models.OverwriteStorage(),
                        upload_to=ideaGen.models.generate_unique_filename,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("parameters", models.JSONField(blank=True, null=True)),
                (
                    "generation_status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("retried", "Retried"),
                            ("pending", "Pending"),
                        ],
                        default="success",
                        max_length=20,
                    ),
                ),
                ("retry_count", models.IntegerField(default=0)),
                ("original_parameters", models.JSONField(blank=True, null=True)),
                ("final_parameters", models.JSONField(blank=True, null=True)),
                (
                    "idea",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="ideaGen.idea",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductIdea2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product", models.CharField(max_length=255)),
                ("brand", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=255)),
                ("dynamic_fields", models.JSONField(default=dict)),
                ("description_length", models.IntegerField(default=70)),
                ("number_of_ideas", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("negative_prompt", models.TextField(blank=True, null=True)),
                (
                    "source_document_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "source_document_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_ideas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="idea",
            name="product_idea",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ideas",
                to="ideaGen.productidea2",
            ),
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "main_project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ideagen_projects",
                        to="core.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ideagen_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_modified"],
            },
        ),
        migrations.AddField(
            model_name="productidea2",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_ideas",
                to="ideaGen.project",
            ),
        ),
    ]
