# Generated by Django 5.1.4 on 2025-02-10 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ideaGen", "0003_delete_projectmodule"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="idea",
            options={"ordering": ["idea_set", "idea_set_label"]},
        ),
    ]
