# Generated by Django 5.1.4 on 2025-02-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ideaGen", "0004_alter_idea_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="idea",
            options={},
        ),
        migrations.AddField(
            model_name="idea",
            name="decomposed_aspects",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="idea",
            name="enhanced_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="idea",
            name="visualization_prompt",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="generatedimage2",
            name="generation_status",
            field=models.CharField(
                choices=[
                    ("success", "Success"),
                    ("failed", "Failed"),
                    ("retried", "Retried"),
                    ("pending", "Pending"),
                ],
                default="success",
                max_length=20,
            ),
        ),
    ]
