# Generated by Django 5.1.4 on 2025-02-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ideaGen", "0005_alter_idea_options_idea_decomposed_aspects_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
