# Generated by Django 5.1.4 on 2025-02-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ideaGen", "0006_alter_project_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="productidea2",
            name="source_document_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="productidea2",
            name="source_document_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
