# Generated by Django 5.1.4 on 2025-06-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userapitokens",
            name="gemini_token",
            field=models.CharField(
                blank=True,
                default="AIzaSyC5Dqjx0DLbkRXH9YWqWZ1SPTK0w0C4oFY",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userapitokens",
            name="huggingface_token",
            field=models.CharField(
                blank=True,
                default="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",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userapitokens",
            name="llama_token",
            field=models.CharField(
                blank=True,
                default="sk-vZTTKgcY3z9idJLCBaTHT3BlbkFJL9axkgC5FdoKyRIcx2B",
                max_length=255,
                null=True,
            ),
        ),
    ]
