# Generated by Django 5.1.4 on 2025-03-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userapitokens",
            name="llama_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
