# Generated by Django 5.1.4 on 2025-02-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="processedindex",
            name="idea_parameters",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
