# Generated by Django 5.1.4 on 2025-06-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_alter_userapitokens_gemini_token_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SSOAllowedUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
