# Generated by Django 5.1.4 on 2025-03-19 16:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_modulepermissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ModulePermissions",
            new_name="UserModulePermissions",
        ),
    ]
