# Generated by Django 5.1.4 on 2025-04-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_userapitokens_llama_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="response_format",
            field=models.CharField(
                blank=True, default="natural", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="response_length",
            field=models.CharField(
                blank=True, default="comprehensive", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="use_web_knowledge",
            field=models.BooleanField(default=False),
        ),
    ]
