# Generated by Django 5.1.4 on 2025-06-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_ssoalloweduser"),
    ]

    operations = [
        migrations.AddField(
            model_name="userapitokens",
            name="nebius_token",
            field=models.CharField(
                blank=True,
                default="eyJhbGciOiJIUzI1NiIsImtpZCI6IlV6SXJWd1h0dnprLVRvdzlLZWstc0M1akptWXBvX1VaVkxUZlpnMDRlOFUiLCJ0eXAiOiJKV1QifQ.eyJzdWIiOiJnb29nbGUtb2F1dGgyfDEwNDA3NjM1MTQxNjY5Mzc1MzgxNiIsInNjb3BlIjoib3BlbmlkIG9mZmxpbmVfYWNjZXNzIiwiaXNzIjoiYXBpX2tleV9pc3N1ZXIiLCJhdWQiOlsiaHR0cHM6Ly9uZWJpdXMtaW5mZXJlbmNlLmV1LmF1dGgwLmNvbS9hcGkvdjIvIl0sImV4cCI6MTkwODA5OTQyNywidXVpZCI6IjY5N2ExOGI1LTVmMjMtNDM4YS1iYmVmLTdhNmYwZGUxYzY2MyIsIm5hbWUiOiJpbWdfZ2VuIiwiZXhwaXJlc19hdCI6IjIwMzAtMDYtMTlUMTE6Mzc6MDcrMDAwMCJ9.X_f-n1ginmJkWBmbkhMt12L-k-fapnoo8ws4WXFWC4E",
                max_length=1024,
                null=True,
            ),
        ),
    ]
