# Generated by Django 5.1.4 on 2025-03-04 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_project_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProjectActivity",
        ),
    ]
