# Generated by Django 5.1.4 on 2025-06-19 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_project_category_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFeaturePermissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "right_panel_access",
                    models.BooleanField(
                        default=True, help_text="Enable/disable entire right panel"
                    ),
                ),
                (
                    "mindmap_generation",
                    models.BooleanField(
                        default=True, help_text="Generate new mindmaps from documents"
                    ),
                ),
                (
                    "mindmap_history",
                    models.BooleanField(
                        default=True, help_text="View previously generated mindmaps"
                    ),
                ),
                (
                    "notes_panel",
                    models.BooleanField(
                        default=True, help_text="Access to notes functionality"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who created/modified these permissions",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_feature_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Feature Permission",
                "verbose_name_plural": "User Feature Permissions",
            },
        ),
    ]
