# Generated by Django 5.1.4 on 2025-04-17 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_project_is_archived"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="is_archived",
        ),
    ]
