# Generated by Django 5.1.4 on 2025-06-12 07:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('follow_up_questions', models.JSONField(blank=True, null=True)),
                ('main_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_histories_NB', to='core.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_histories_NB', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('citations', models.JSONField(blank=True, null=True)),
                ('use_web_knowledge', models.BooleanField(default=False)),
                ('response_length', models.CharField(blank=True, default='comprehensive', max_length=20, null=True)),
                ('response_format', models.CharField(blank=True, default='natural', max_length=50, null=True)),
                ('chat_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_NB', to='notebook.chathistory')),
            ],
        ),
        migrations.CreateModel(
            name='ConversationMemoryBuffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_entities', models.JSONField(blank=True, null=True)),
                ('context_summary', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memory_buffer_NB', to='notebook.chathistory')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('main_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_documents_NB', to='core.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebook_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chathistory',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='chat_histories_NB', to='notebook.document'),
        ),
        migrations.CreateModel(
            name='MindMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(help_text='JSON data for the mindmap structure')),
                ('document_sources', models.JSONField(blank=True, help_text='List of document filenames used to generate this mindmap', null=True)),
                ('total_nodes', models.PositiveIntegerField(default=0, help_text='Total number of nodes in the mindmap')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mindmaps_NB', to='core.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mindmaps_NB', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_converted_to_document', models.BooleanField(default=False)),
                ('converted_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_note', to='notebook.document')),
                ('main_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes_NB', to='core.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebook_notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faiss_index', models.CharField(help_text='Path to saved FAISS index file', max_length=255)),
                ('metadata', models.CharField(help_text='Path to saved metadata file', max_length=255)),
                ('summary', models.TextField(help_text='Generated summary of the document')),
                ('idea_parameters', models.JSONField(blank=True, null=True)),
                ('markdown_path', models.CharField(help_text='Path to saved Markdown file with key terms', max_length=255)),
                ('follow_up_question_1', models.TextField(blank=True, help_text='First follow-up question', null=True)),
                ('follow_up_question_2', models.TextField(blank=True, help_text='Second follow-up question', null=True)),
                ('follow_up_question_3', models.TextField(blank=True, help_text='Third follow-up question', null=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('key_points', models.JSONField(blank=True, default=list, help_text='Key points/topics extracted from document')),
                ('mindmap_generated', models.BooleanField(default=False, help_text='Whether a mindmap has been generated from this document')),
                ('last_mindmap_generated', models.DateTimeField(blank=True, help_text='When was the last mindmap generated', null=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='notebook.document')),
            ],
        ),
        migrations.CreateModel(
            name='UserAPITokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('huggingface_token', models.CharField(blank=True, max_length=255, null=True)),
                ('gemini_token', models.CharField(blank=True, max_length=255, null=True)),
                ('llama_token', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens_NB', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserModulePermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disabled_modules', models.JSONField(blank=True, default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions_NB', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserUploadPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_upload', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='upload_permissions_NB', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
