# Generated by Django 5.1.4 on 2025-06-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notebook", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userapitokens",
            name="huggingface_token",
        ),
        migrations.AddField(
            model_name="userapitokens",
            name="nebius_token",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
