# Generated by Django 5.1.4 on 2025-06-11 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
        ("notebook", "0002_processedindex_key_points_note"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="processedindex",
            name="last_mindmap_generated",
            field=models.DateTimeField(
                blank=True, help_text="When was the last mindmap generated", null=True
            ),
        ),
        migrations.AddField(
            model_name="processedindex",
            name="mindmap_generated",
            field=models.BooleanField(
                default=False,
                help_text="Whether a mindmap has been generated from this document",
            ),
        ),
        migrations.CreateModel(
            name="MindMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.JSONField(help_text="JSON data for the mindmap structure"),
                ),
                (
                    "document_sources",
                    models.JSONField(
                        blank=True,
                        help_text="List of document filenames used to generate this mindmap",
                        null=True,
                    ),
                ),
                (
                    "total_nodes",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of nodes in the mindmap"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "main_project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mindmaps_NB",
                        to="core.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mindmaps_NB",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
