# Generated by Django 5.1.4 on 2025-07-01 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_category_user"),
        ("notebook", "0002_remove_userapitokens_huggingface_token_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("document_upload", "Document Upload"),
                            ("conversation_create", "Conversation Create"),
                            ("chat_message", "Chat Message"),
                            ("document_delete", "Document Delete"),
                            ("conversation_delete", "Conversation Delete"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "document_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("document_id", models.IntegerField(blank=True, null=True)),
                (
                    "conversation_title",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("conversation_id", models.UUIDField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "main_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notebook_transactions",
                        to="core.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notebook_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("file_type", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "processing_status",
                    models.CharField(default="completed", max_length=50),
                ),
                ("upload_method", models.CharField(default="regular", max_length=50)),
                (
                    "user_transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notebook_document_details",
                        to="notebook.usertransaction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConversationTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_count", models.PositiveIntegerField(default=0)),
                ("input_api_tokens", models.PositiveIntegerField(default=0)),
                ("output_api_tokens", models.PositiveIntegerField(default=0)),
                ("total_tokens_used", models.PositiveIntegerField(default=0)),
                ("web_knowledge_used", models.BooleanField(default=False)),
                ("response_format", models.CharField(default="natural", max_length=50)),
                (
                    "response_length",
                    models.CharField(default="comprehensive", max_length=20),
                ),
                (
                    "user_transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notebook_conversation_details",
                        to="notebook.usertransaction",
                    ),
                ),
            ],
        ),
    ]
